version: '3.7'

services:
  db_test:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: blog
#      POSTGRES_LOGIN: postgres
#      USERLOGIN: "${USERLOGIN}"
#      PASSWORD: "${PASSWORD}"
#      DB: db_test