spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: admin
  data:
    mongodb:
      host: localhost
      port: 9092
      database: mongodb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
  logging:
    file:
      path: logs
server:
  port: 8080

constraints:
  outputLimit: 5
