spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
  logging:
    file:
      path: logs
server:
  port: 8080

properties:
  outputLimit: 5
